# fly.toml file generated for ra-backend on 2023-04-14T21:19:42+03:00

app = "ra-backend"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "waw"
processes = []

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
